org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=moremousekeybinds
mod.name=MoreMouseKeybinds
mod.group=me._12emin34
mod.version=3.0.0
mod.channel_tag=
mod.authors=12emin34
mod.contributors=
mod.license=LGPL-3.0
mod.description=Adds in some useful utility/accessibility features that are toggled using keybinds.
mod.sources_url=https://github.com/12emin34/MouseMouseKeybinds
mod.homepage_url=https://modrinth.com/mod/moremousekeybinds
mod.issues_url=https://github.com/12emin34/MouseMouseKeybinds/issues
mod.discord_url=https://discord.gg/4uPqEzc3Us

deps.minecraft=[VERSIONED]
deps.parchment=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.mixson=[VERSIONED]
deps.mixinconstraints=1.1.0
deps.modmenu=[VERSIONED]
deps.fzzy_config=[VERSIONED]

publish.modrinth=
publish.curseforge=
publish.github=false
